service: line-ai-chat
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-1
  logRetentionInDays: 14

plugins:
  - serverless-plugin-typescript

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: post
