service: line-ai-chat
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-1
  logRetentionInDays: 14

plugins:
  - serverless-plugin-typescript

functions:
  api:
    handler: index.handler
    timeout: 60 # Lambdaのタイムアウト時間
    events:
      - httpApi:
          path: /
          method: post
